import { notFound } from "next/navigation";
import { AppShell } from "@/components/layout/app-shell";
import { BuilderPublicPage } from "@/components/builder/builder-public-page";
import { builderPublicPath } from "@/config/builder-pages";
import { buildPageMetadata } from "@/lib/seo";
import { getSession } from "@/lib/session";
import { getBuilderPageData } from "@/server/services/builder-page.service";

export const dynamicParams = true;

/**
 * Builder slugs are generated by slugify(): lowercase letters, digits, and hyphens only. Anything
 * else (e.g. /llms-small.txt, /wp-login.php) cannot be a builder, so 404 before any session or DB work.
 */
const BUILDER_SLUG_RE = /^[a-z0-9]+(?:-[a-z0-9]+)*$/i;

interface PageProps {
  params: Promise<{ slug: string }>;
}

export async function generateMetadata({ params }: PageProps) {
  const { slug } = await params;
  if (!BUILDER_SLUG_RE.test(slug)) notFound();
  const session = await getSession();
  const data = await getBuilderPageData(slug, session?.id);

  // notFound() here (not just in the page): for crawlers metadata renders before streaming starts,
  // so this sends a real 404 status instead of a 200 "soft 404" (see htmlLimitedBots in next.config).
  if (!data) notFound();

  return buildPageMetadata({
    title: `${data.profile.fullName} — Developer Profile`,
    description: data.description,
    keywords: [
      data.profile.fullName,
      `${data.profile.fullName} projects`,
      "off-plan developer Pakistan",
      "AbadRaho builder",
    ],
    path: builderPublicPath(slug),
  });
}

export default async function BuilderProfilePage({ params }: PageProps) {
  const { slug } = await params;
  if (!BUILDER_SLUG_RE.test(slug)) notFound();
  const session = await getSession();
  const data = await getBuilderPageData(slug, session?.id);
  if (!data) notFound();

  return (
    <AppShell>
      <BuilderPublicPage data={data} />
    </AppShell>
  );
}
