/** @deprecated Use `flattenAdminNav(getAdminNavGroups())` from `@/config/admin-nav`. */
export const adminNav = [
  { href: "/admin/dashboard", label: "Dashboard" },
  { href: "/admin/projects", label: "Projects" },
  { href: "/admin/projects/pending", label: "Pending projects" },
  { href: "/admin/projects/active", label: "Active projects" },
  { href: "/admin/units", label: "Units" },
  { href: "/admin/areas", label: "Areas" },
  { href: "/admin/project-types", label: "Project types" },
  { href: "/admin/builders", label: "Builders" },
  { href: "/admin/users", label: "Users" },
  { href: "/admin/agents", label: "Agents / Brokers" },
  { href: "/admin/inquiries", label: "Inquiries (Zoho)" },
  { href: "/admin/search-history", label: "Search history" },
  { href: "/admin/vouchers", label: "Vouchers" },
  { href: "/admin/blogs", label: "Blogs" },
  { href: "/admin/blog-categories", label: "Blog categories" },
  { href: "/admin/tags", label: "Tags" },
  { href: "/admin/progress", label: "Progress" },
  { href: "/admin/room-types", label: "Room types" },
  { href: "/admin/amenities", label: "Amenities" },
  { href: "/admin/utilities", label: "Utilities" },
  { href: "/admin/contact", label: "Contact messages" },
  { href: "/admin/payment-schedules", label: "Payment schedules" },
  { href: "/admin/reviews", label: "Reviews" },
  { href: "/admin/teams", label: "Teams" },
  { href: "/admin/activity-log", label: "Activity log" },
  { href: "/admin/customers", label: "Customers" },
  { href: "/admin/favorites", label: "Favorites" },
  { href: "/admin/import", label: "CSV import" },
  { href: "/admin/profile", label: "Admin profile" },
  { href: "/admin/login", label: "Admin login" },
] as const;
